# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('scene', models.CharField(max_length=200)),
                ('choice_number', models.PositiveIntegerField(verbose_name='choice number')),
                ('choice_value', models.PositiveIntegerField(verbose_name='choice value')),
            ],
        ),
    ]
