# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnovel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='choice_number',
        ),
        migrations.RemoveField(
            model_name='log',
            name='choice_value',
        ),
        migrations.AddField(
            model_name='log',
            name='action_number',
            field=models.PositiveIntegerField(default=0, verbose_name='action number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='action_value',
            field=models.PositiveIntegerField(default=0, verbose_name='action value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
