# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnovel', '0002_auto_20160308_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_value',
            field=models.CharField(max_length=200),
        ),
    ]
